AllenNeuralDynamics/aind-data-schema-models

src/aind_data_schema_models/species.py

adding NCBI:txid prefix to taxonomy IDs

---

src/aind_data_schema_models/specimen_procedure_types.py

closes #19 
Adds `Expansion` to the list of `SpecimenProcedureTypes`

Add Expansion Specimen Procedure Type

---

src/aind_data_schema_models/organizations.py

closes #23 
Adding NIMH as a funder
name = National Institute of Mental Health
abbreviation = NIMH
ror = [04xeg9z08](https://ror.org/04xeg9z08)

adding NIMH funder

---

src/aind_data_schema_models/units.py

add voltage unit

---

src/aind_data_schema_models/organizations.py

closes #38 
Name: Emory University
abbr: Emory
RORID: 03czfpz43

adding emory to organizations

---

.github/workflows/publish_models_dev.yml
.github/workflows/publish_models_main.yml

hot-fix: fixes python script path

---

src/aind_data_schema_models/_generators/models/organizations.csv
src/aind_data_schema_models/mouse_anatomy.py
src/aind_data_schema_models/organizations.py

Feat interoception 2

---

src/aind_data_schema_models/_generators/templates/organizations.txt
src/aind_data_schema_models/organizations.py

I was handling this wrong for the schema, so this should solve it.

added list of places for catheter implants

---

src/aind_data_schema_models/_generators/templates/mouse_anatomy.txt
src/aind_data_schema_models/_generators/templates/organizations.txt
src/aind_data_schema_models/mouse_anatomy.py
src/aind_data_schema_models/organizations.py

This got dropped off because I was doing it wrong

Blood vessels

---

src/aind_data_schema_models/_generators/templates/organizations.txt
src/aind_data_schema_models/organizations.py

updates sublists

---

src/aind_data_schema_models/_generators/models/modalities.csv
src/aind_data_schema_models/_generators/templates/modalities.txt
src/aind_data_schema_models/modalities.py

This PR removes session and rig from the file requirements matrix, this is a blocking PR for upstream code in aind-data-schema v2.0

feat: updating file requirements for 1.0 release

---

src/aind_data_schema_models/__init__.py

fix: bump branch to 2.0.0

---

src/aind_data_schema_models/_generators/models/organizations.csv
src/aind_data_schema_models/_generators/templates/organizations.txt
src/aind_data_schema_models/organizations.py

Following up on https://github.com/AllenNeuralDynamics/aind-data-schema/issues/1285#issue-2885878169

feat: add new organization models for MIT, MIBR, BCS, UCSD, JHU, and BU

---

src/aind_data_schema_models/_generators/templates/mouse_anatomy.txt
src/aind_data_schema_models/mouse_anatomy.py

Adds a GroundWireLocations convenience list with brain and skull, plus the body parts list

feat: add GroundWireLocations

---

src/aind_data_schema_models/_generators/models/atlas.csv
src/aind_data_schema_models/_generators/templates/atlas.txt
src/aind_data_schema_models/atlas.py
src/aind_data_schema_models/mouse_anatomy.py
tests/test_atlas.py

PR also fixes a mistake in a previous PR, which didn't include the actual changes to `mouse_anatomy.py` for InjectionTargets

Feat: introduce new AtlasName model

---

src/aind_data_schema_models/licenses.py
src/aind_data_schema_models/system_architecture.py
tests/test_licenses.py

Feat model updates

---

src/aind_data_schema_models/_generators/models/specimen_procedure_types.csv
src/aind_data_schema_models/specimen_procedure_types.py

added Barseq to specimen procedures

---

src/aind_data_schema_models/_generators/models/process_names.csv
src/aind_data_schema_models/process_names.py

We need to include radial correction in the list of processes for the Z1 image processing pipeline.
@dyf @saskiad @dbirman

including radial correction to the list of processes

---

CODE_OF_CONDUCT.md

- Adds Code of Conduct as per https://github.com/AllenNeuralDynamics/aind-library-template/issues/83

docs: adds code of conduct

---

README.md

PR adds some information about how the updated documentation in `aind-data-schema` is affected by changes to the models repository and cleans up some other parts of the documentation.

docs: small updates to docs

---

src/aind_data_schema_models/_generators/models/organizations.csv
src/aind_data_schema_models/_generators/models/specimen_procedure_types.csv
src/aind_data_schema_models/devices.py
src/aind_data_schema_models/organizations.py
src/aind_data_schema_models/specimen_procedure_types.py

closes #200 
closes #195 
closes #194

Feat couplesmallthings

---

src/aind_data_schema_models/_generators/models/species.csv
src/aind_data_schema_models/species.py

PR adds several new species with their NCBI taxonomy IDs. See https://www.ncbi.nlm.nih.gov/datasets/taxonomy/tree/ to double check any of them.

feat: add new species

---

src/aind_data_schema_models/_generators/models/registries.csv
src/aind_data_schema_models/registries.py

Feat 202 uniprot

---

src/aind_data_schema_models/_generators/models/organizations.csv
src/aind_data_schema_models/_generators/templates/organizations.txt
src/aind_data_schema_models/organizations.py

Feat 207 upennv2

---

src/aind_data_schema_models/_generators/models/organizations.csv
src/aind_data_schema_models/_generators/templates/organizations.txt
src/aind_data_schema_models/organizations.py

Feat 214 lasers

---

src/aind_data_schema_models/_generators/models/species.csv
src/aind_data_schema_models/_generators/templates/brain_atlas.txt
src/aind_data_schema_models/_generators/templates/species.txt
src/aind_data_schema_models/brain_atlas.py
src/aind_data_schema_models/species.py

PR also fixes a bug in brain_atlas that was triggered when I ran the run_all.sh script.

feat: Add common names for species

---

src/aind_data_schema_models/_generators/models/organizations.csv
src/aind_data_schema_models/_generators/templates/organizations.txt
src/aind_data_schema_models/organizations.py

Feat 235 arduino

---

src/aind_data_schema_models/_generators/models/modalities.csv
src/aind_data_schema_models/modalities.py

adding CCF modalities

---

src/aind_data_schema_models/_generators/models/process_names.csv
src/aind_data_schema_models/process_names.py

added skeleton to process names

---

src/aind_data_schema_models/units.py

PR adds `TorqueUnit.NM` for SI torque unit.

feat: TorqueUnit
