AllenNeuralDynamics/aind-data-schema-models

src/aind_data_schema_models/organizations.py

closes #5 
Adds the organization `Midwest Optical Systems` to `organizations.py`
Abbr: `MidOpt`
RORID: none
Adds org to list `FILTER_MANUFACTURERS`

add midwest optical to organizations

---

src/aind_data_schema_models/organizations.py
tests/test_specimen_procedure_types.py

closes #18 
Adds 5 funders:
Chan Zuckerberg Initiative (CZI). ror = [02qenvm24](https://ror.org/02qenvm24)
National Center for Complementary & Integrative Health (NCCIH). ror = [00190t495](https://ror.org/00190t495)
Michael J. Fox Foundation for Parkinson's Research (MJFF). ror = [03arq3225](https://ror.org/03arq3225)
Templeton World Charity Foundation (TWCF). ror = [00x0z1472](https://ror.org/00x0z1472)
MBF Bioscience. Ror=[02zynam48](https://ror.org/02zynam48)

adding new funding orgs

---

src/aind_data_schema_models/organizations.py

closes #28 
Adds:
name: Integrated DNA Technologies
abbreviation: IDT
rorid: https://ror.org/009jvpf03
Currently does not add this to any manufacturer/funder lists

Add IDT to organizations list

---

src/aind_data_schema_models/platforms.py

This adds motor observatory platform. 
I think it would be useful to have a separate platform to include data from my rig that would combine 3D tracking with either EMG or fiber photometry.

feat(platform): add new motor observatory platform

---

src/aind_data_schema_models/registry.py

closes #39 
Adding to registries: 
name: Edinburgh Mouse Atlas Project
abbreviation: EMAPA

adding EMAPA to registries

---

src/aind_data_schema_models/organizations.py

Mesoscope uses a Chameleon laser and Lumen Dynamics epi lamp. Adding for mesoscope rig json

adding two orgs to laser and lamp models

---

src/aind_data_schema_models/utils.py
tests/test_organizations.py

empty fields were mapping to "None" instead of `None`

fixing bug with nulls

---

pyproject.toml

Time boxed attempt to fix this on 2.6.4 didn't work out, bumping minimum version number for pydantic

fix: update to pydantic minimum 2.7 to avoid annotation errors

---

pyproject.toml

PR pins the version of aind-flake8-extensions so it only warns about missing default= and doesn't add the new extension I put in v0.6.0 (which currently causes the linter tests to fail in aind-data-schema and aind-data-schema-models)

ci: pin aind-flake8-extensions

---

src/aind_data_schema_models/units.py
tests/test_units.py

BREAKING CHANGE: removes all XValue classes
The intention is to replace these with validators to check that units are included with values
There are only a few places these are being used:
https://github.com/AllenNeuralDynamics/SPIM-UI-Launch/blob/342d357be6aec3798aefe3b6d6ed4d1397678d57/exaSPIM/exaSPIM-UI-Luanch.py#L5
https://github.com/AllenNeuralDynamics/SPIM-UI-Launch/blob/342d357be6aec3798aefe3b6d6ed4d1397678d57/iSPIM/iSPIM-UI-Launch.py#L5
and a few places in aind-data-schema although confusingly it's used in the tests but not in the actual schema?

perf: remove XValue unit value combinations

---

src/aind_data_schema_models/models/organizations.csv

closes #90 
Adjusts spelling from `Sigma-Aldritch` -> `Sigma-Aldrich`

Sigma-Aldrich misspelled

---

src/aind_data_schema_models/data_name_patterns.py

Basically does what it says in the title.
This would allow us to label data from motor observatory and other experiments coming out from the NBA team as group="NBA" in the data description.

add NBA group for data description

---

src/aind_data_schema_models/data_name_patterns.py
tests/test_data_name_patterns.py
tests/test_models.py

This PR updates the `date_name_patterns.datetime_to_name_string` function to use the new pattern `YYYY-MM-DDTHHMMSS`. It also deprecates the `datetime_from_name_string` function in favor of using `datetime.fromisoformat`
It also updates the data name to the pattern `<subject_id>_<datetime>` instead of `<label>_<date>_<time>`

refactor: update to/from datename to isoformat compatible pattern

---

src/aind_data_schema_models/_generators/templates/mouse_anatomy.txt
src/aind_data_schema_models/mouse_anatomy.py

This PR adds common injection targets, to simplify targeting in the `Procedures.Injection` class when targeting parts of the body

feat: add injection targets (RO and IP injections)

---

pyproject.toml
src/aind_data_schema_models/_generators/dev_utils.py
src/aind_data_schema_models/_generators/generator.py
src/aind_data_schema_models/utils.py
tests/test_generator.py
tests/test_pid_names.py

This PR sets a lower bound on the version of the package `black` and enforces it in the generator code. Users can no longer call the main run script without a compatible version.
Apparently nobody has run black on the src/ folder in a while because it also wanted to change a few docstrings.

feat: set a lower bound on the version of the black package

---

src/aind_data_schema_models/coordinates.py

PR adds `AnatomicalRelative.ORIGIN` for use in situations where an object or position is on the origin but we require users to specify an `AnatomicalRelative` position.

feat: add an origin concept for AnatomicalRelative

---

src/aind_data_schema_models/coordinates.py
src/aind_data_schema_models/data_name_patterns.py
tests/test_data_name_patterns.py

This PR makes two breaking changes:
- It reverts the changes we made to the datetime pattern to use `YYYY-MM-DD_HH-MM-SS` instead of the isoformat compatible plan for 2.0 of `THHMMSS`
- It changes the `AxisDirection.BT` and `TB` to `DU` and `UD`. This is so that there isn't a name clash with the forward-to-back axis, which was causing problem for devices. In the future all axis direction acronyms need to be unique.

breaking change: Revert datetime pattern and change direction bottom_to_top to down_to_up

---

src/aind_data_schema_models/_generators/models/stimulus_modality.csv
src/aind_data_schema_models/_generators/templates/stimulus_modality.txt
src/aind_data_schema_models/stimulus_modality.py
tests/test_stimulus_modality.py

This PR moves StimulusModality from aind-data-schema into the models repo. It also replaces StimulusModality.NONE with StimulusModality.NO_STIMULUS due to a limitation in how the jinja2 templates work.

feat: add StimulusModality

---

src/aind_data_schema_models/_generators/templates/brain_atlas.txt
src/aind_data_schema_models/brain_atlas.py
tests/test_brain_atlas.py
tests/test_models.py

This PR removes the use of subclasses for CCFStructure and replaces them with direct instantiations of the objects.

breaking change: remove use of BrainStructureModel subclasses for CCF

---

src/aind_data_schema_models/_generators/models/species.csv
src/aind_data_schema_models/_generators/templates/species.txt

This PR fixes model publishing to docdb, which depended on the existence of a "name" field.

fix: replace "species" with "name" in species.csv

---

src/aind_data_schema_models/coordinates.py

Adds between-vertebrae origins for spinal injections. This allows us to specify origins for spinal injections that directly align with the way they are specified in the surgical request form.
Closes: https://github.com/AllenNeuralDynamics/aind-data-schema/issues/1564
Should be merged alongside this documentation PR: https://github.com/AllenNeuralDynamics/aind-data-schema/pull/1565

Added between-vertebrae origins for spinal injections
